version: "3.9"
services:
  broker:
    build: ./broker
    container_name: osensa-mosquitto
    environment:
      - PORT=8083
    ports:
      - "1883:1883"
      - "8083:8083"
    restart: unless-stopped